project:
  type: website
  output-dir: docs
website:
  title: "AFROMAPR 2025"
  navbar:
    left:
      - text: "A propos"
        menu:
          - text: "Objectifs de l'EE 2025"
            href: index.qmd
      - text: "STATISTIQUES AVEC R"
        menu: 
        - text: "---- R & R STUDIO : OFFICE KILLER ----"
        - href: STAT0-Excel_Killer.qmd
          text: "Les programmes R : Excel Killer ?"
        - href: STAT0-Word_Killer.qmd
          text: "Les documents Rmd : Word Killer ?"
        - text: "--- STAT1: VARIABLES STATISTIQUES ----"
        - href: STAT1-Variables-Cours.qmd
          text: "Cours : Types de variables"  
        - href: STAT1-Exo1.qmd
          text: "Exo1 : Premiers pas dans R"
        - href: STAT1-Exo2.qmd
          text: "Exo2 : Les femmes du Bénin"
        - text: "---- STAT2 : STATISTIQUE EXPLORATOIRE----"
        - href: STAT2-Explor-Cours.qmd
          text: "Cours : Exploration avec R-base"
        - href: STAT2-Exo1.qmd
          text: "Exo1 : Manipuler des tableaux"
        - href: STAT2-Exo2.qmd
          text: "Exo2 : Résumer des variables"  
        - text: "---- STAT3 : CORRELATION & REGRESSION ----"
        - href: STAT3-Correlation-Cours.qmd
          text: "Cours : Corrélation"
        - href: STAT3-Regression-Cours.qmd
          text: "Cours : Régression linéaire"
        - href: STAT3-Exo1.qmd
          text: "Exo1 : Programme-type"
        - text: "---- STAT4 : ENQUETES & TEST DU CHI2 ----"
        - href: STAT4-Enquetes.qmd
          text: "Cours : Echantillonage"
        - href: STAT4-chi2.qmd
          text: "Cours : Test du chi-2"
        - href: STAT4-Exo1.qmd
          text: "Exo1 : Programme-type"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/StatR
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, FR CIST
format:
  html:
    grid:
      sidebar-width: 100px
    theme: 
      light: minty    
      dark: solar
    css: style.scss
    toc: true


