project:
  type: website
  output-dir: docs
website:
  title: "AFROMAPR 2025"
  navbar:
    left:
      - text: "A propos"
        menu:
          - text: "Objectifs de l'EE 2025"
            href: index.qmd
      - text: "STATISTIQUES AVEC R"
        menu: 
        - text: "---- R & R STUDIO : OFFICE KILLER ----"
        - href: STAT0-Excel_Killer.qmd
          text: "Les programmes R : Excel Killer ?"
        - href: STAT0-Word_Killer.qmd
          text: "Les documents Rmd : Word Killer ?"
        - text: "--- STAT1: VARIABLES STATISTIQUES ----"
        - href: STAT1-Variables-Cours.qmd
          text: "Cours : Types de variables"  
        - href: STAT1-Exo1.qmd
          text: "Exo1 : Premiers pas dans R"
        - href: STAT1-Exo2.qmd
          text: "Exo2 : Les femmes du Bénin"
        - text: "---- STAT2 : STATISTIQUE EXPLORATOIRE----"
        - href: STAT2-Explor-Cours.qmd
          text: "Cours : Exploration avec R-base"
        - href: STAT2-Exo1.qmd
          text: "Exo1 : Manipuler des tableaux"
        - href: STAT2-Exo2.qmd
          text: "Exo2 : Résumer des variables"  
        - text: "---- STAT3 : CORRELATION & REGRESSION ----"
        - href: STAT3-Correlation-Cours.qmd
          text: "Cours : Corrélation"
        - href: STAT3-Regression-Cours.qmd
          text: "Cours : Régression linéaire"
        - href: STAT3-Exo1.qmd
          text: "Exo1 : Programme-type"
        - text: "---- STAT4 : ENQUETES & TEST DU CHI2 ----"
        - href: STAT4-Enquetes.qmd
          text: "Cours : Echantillonage"
        - href: STAT4-chi2.qmd
          text: "Cours : Test du chi-2"
        - href: STAT4-Exo1.qmd
          text: "Exo1 : Programme-type"
      - text: "CARTOGRAPHIE AVEC MAGRIT"
        menu:     
        - text: "---- MAGRIT 1 : PREMEIRS PAS ----"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT1/MAGRIT1.pptx
          text: "Cours (.pptx)"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT1.zip
          text: "Exercice (dossier)"    
        - text: "---- MAGRIT 2 : STOCKS ET TAUX ----"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT2/MAGRIT2.pdf 
          text: "Cours (.pdf)"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT2.zip
          text: "Exercice (dossier)" 
        - text: "---- MAGRIT 3 : SELECTION ET AGREGATION ----"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT3/MAGRIT3.pptx
          text: "Cours (.pptx)"
        - href: https://github.com/worldregio/StatR/raw/refs/heads/main/MAGRIT/MAGRIT3.zip
          text: "Exercice (dossier)"       
      - text: "GEOMATIQUE"
        menu:  
        - href: Raster.html
          text: "Manipuler des données raster avec R et Terra" 
      - text: "KOBO"
        menu:  
        - href: https://ee2023.netlify.app/modules/out3_kobo
          text: "Prise en main (EE CIST 2023)"          
      - text: "ATELIERS"
        menu:            
        - href: Atelier1.qmd
          text: "Atelier1 : Agriculture"  
        - href: Atelier2.qmd
          text: "Atelier2 : Démographie" 
        - href: Atelier3.qmd
          text: "Atelier3 : Eau" 
        - href: Atelier4.qmd
          text: "Atelier4 : Mines" 
        - href: Atelier5.qmd
          text: "Atelier5 : Santé" 
        - href: Atelier6.qmd
          text: "Atelier6 : Urbanisation" 
        - href: Atelier7.qmd
          text: "Atelier7 : Transport"           
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/StatR
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, FR CIST
format:
  html:
    grid:
      sidebar-width: 100px
    theme: 
      light: minty    
      dark: solar
    css: style.scss
    toc: true


